### PR TITLE
Update HACS URL

### PR DESCRIPTION
**Pull request by wrt54g**
I updated the HACS Badge URL to the new hacs/integration.

### CODE REVIEW

**Comment by wrt54g** [comment]
no stale

**Comment by blizzrdof77** [comment]
Looks good to me.

@thomasloven -- any reason you aren't accepting this PR?

**Comment by thomasloven** [comment]
Only that github seems to be entirely random in which PRs it tells me about...

**Comment by thomasloven** [comment]
Thanks again!

**Pull request merged**
