### PR TITLE
Fixes #587

### LINKED ISSUE #587: Popup Title Styles Changed in 2023.6.0
My Home Assistant version: 2023.6.0b4

**What I am doing:**
Showing a popup with `browser_mod.popup` in several locations in my dashboard.
image

It looks like this change in the frontend is to blame for the restructure, removing the old `main-title` class:
https://github.com/home-assistant/frontend/pull/16485

**What I expected to happen:**
Styled the same as a more-info dialog

**What happened instead:**
Title text is showing as normal font on next line

**Minimal** steps to reproduce:
Use a popup service call in 2023.6.0b3+

```yaml
      - type: custom:mushroom-cover-card
        entity: cover.island_shades
        hold_action:
          action: fire-dom-event
          haptic: success
          browser_mod:
            service: browser_mod.popup
            data:
              title: Island Shades
              content:
                type: vertical-stack
                cards:
                  - type: custom:mushroom-cover-card
                    entity: cover.island_shades
                    name: All Island Shades
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

### PR DESCRIPTION
**Pull request by bendikrb**

### CODE REVIEW

**Comment by Xitro01** [comment]
This fixed the issue for me, thanks alot for your work!

**Comment by FelixLttks** [comment]
thank you for fixing it

**Comment by deluxestyle** [comment]
even with this I still have the issue on IOS

**Comment by sroebert** [comment]
> even with this I still have the issue on IOS

It does, but you have to reset the front-end cache to see the changes on iOS. (You can do this in the companion app settings)

**Comment by thomasloven** [comment]
Thanks a lot!

**Pull request merged**
