### PR TITLE
Add support for hass actions event

### PR DESCRIPTION
**Pull request by piitaya**
Custom card can now use `hass-action` to execute action https://developers.home-assistant.io/blog/2023/07/07/action-event-custom-cards). This PR forward the event from the popup to the home assistant base object.

Fixes https://github.com/thomasloven/hass-browser_mod/issues/598

### CODE REVIEW

**Comment by piitaya** [comment]
Yes, tested in my dev env

https://github.com/thomasloven/hass-browser_mod/assets/5878303/e2a7f164-b955-47d5-94c0-8ac44262313d

**Comment by ivandelhoyo** [comment]
and how do you modify it? It still doesn't work for me and I don't know how to fix it. Thank you

**Comment by Schlichi83** [comment]
When will there be a new version? Or do you have to manually update browser_mod?

**Comment by smartqasa** [comment]
I did the following with no success:

1. Uninstalled the integration from the Integrations tab (Devices & Services).
2. Deleted the integration from HACS.
3. Manually copied the files from github (https://github.com/thomasloven/hass-browser_mod/tree/master/custom_components/browser_mod) to my system (config/custom_components/browser_mod).
4. Cleared cache on my browsers.
5. Reinstalled the integration from the Integrations tab (Devices & Services).

I don't see any updates on the github repository. Is there another place from which I should download the files?

**Comment by remocamenisch** [comment]
> and how do you modify it? It still doesn't work for me and I don't know how to fix it. Thank you

same here

**Pull request merged**
