### PR TITLE
Add window reload functionality

### PR DESCRIPTION
**Pull request by SBado**
Added a "window-reload" service as described [in this issue](https://github.com/thomasloven/hass-browser_mod/issues/35#issuecomment-583898141).

Also, fixed a couple of import errors.

### CODE REVIEW

**Comment by SBado** [comment]
Is there a chance this teeny tiny PR will ever be reviewed and maybe merged?

**Comment by RJ** [comment]
was about to add this.. but here we are.  please merge!
and thanks for this integration Thomas, it's working nicely with my fully kiosked tablet 👍

**Comment by igloo15** [comment]
Any update on when or if this will be added?

**Comment by KTibow** [comment]
@SBado mind resolving the merge conflicts, by creating a PR **from** the original **to** your fork?

**Comment by donkawechico** [comment]
I went ahead and recreated @SBado's PR [here](https://github.com/thomasloven/hass-browser_mod/pull/134) (with full credit to him and his work!) in the hopes of speeding this along (I'm really excited to have this feature).

But please don't hesitate to fix and merge this one first as OP deserves the credit. Thanks for doing this @SBado!

**Comment by SBado** [comment]
Sorry for the delay, conflicts fixed.

**Comment by KTibow** [comment]
Conflicts still don't seem to be fixed.
image

**Comment by donkawechico** [comment]
> Conflicts still don't seem to be fixed.
> image

They _were_ fixed. Then more showed up :)

**Comment by thomasloven** [comment]
Sorry

**Comment by SBado** [comment]
Confilcts fixed.

**Comment by thomasloven** [comment]
Nice! Thank you!

**Pull request merged**
