### PR TITLE
Update select path to ha-sidebar

### LINKED ISSUE #570: Sidebar order EDIT button KO
My Home Assistant version: 2023.4.2

**What I am doing:**
Trying to reorder sidebar items with BrowserMod.
In Frontend Settings -> Sidebar order -> Click on EDIT button

**What I expected to happen:**
Items in sidebar can be reordered or deleted

**What happened instead:**
Nothing

**Error messages from the browser console:**

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'editMode')
    at he.toggleEditSidebar (browser_mod_panel.js:252:1545)
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

### PR DESCRIPTION
**Pull request by bendikrb**
Fixes #570

### CODE REVIEW

**Comment by oneseventhree** [comment]
please approve this

**Comment by raymercury** [comment]
Tested it on own machine.
This does fix setting "Sidebar order", but the setting "Hide sidebar" is also broken.
I can't set the "Hide sidebar" setting for each User or Browser.
image

**Comment by raymercury** [comment]
Did some digging...

Since HA 2023.4, [edge swipe (to open sidebar) has been broken](https://github.com/home-assistant/android/issues/3460).
Which led to the ["Hide header" issue](https://github.com/thomasloven/hass-browser_mod/issues/566).
I realized that edge swipe for the HA companion app is broken for android, but not iOS for some reason.
Found a fix by loading a js module [hass-sidebar-swipe made by @breakthestatic](https://github.com/breakthestatic/hass-sidebar-swipe)

Browser Mod "Hide header" is still not fixed, but using [kiosk-mode](https://github.com/maykar/kiosk-mode) is a temporary workaround to hide the sidebar which disables swipe to open.

**Comment by thomasloven** [comment]
Have you found any case where `document.body` is strictly necessary?

**Comment by thomasloven** [comment]
Thanks!

**Pull request merged**
