### PR TITLE
Added Media source support

### PR DESCRIPTION
**Pull request by gadgetchnnel**
Added media source support to allow playing of media from HA 2022.3
As this uses helpers introduced in that version, the minimum version of HA is also increased.

### CODE REVIEW

**Comment by 5lamca** [comment]
Well this fixed my issue of not playing media in updated hass... thanks @gadgetchnnel

**Comment by thomasloven** [comment]
Cool! Thanks a lot!

**Comment by kylevidrine** [comment]
how do i add support to ha for media player to allow playing from radio browser?

**Comment by thomasloven** [comment]
https://www.home-assistant.io/integrations/radio_browser/

**Pull request merged**
