### PR TITLE
Fix more-info popup not working

### LINKED ISSUE #719: Popup Card is no longer working
My Home Assistant version: 0.XX.X

**What I am doing:**
I am using popup cards within browser_mod to open up remotes for my tvs when the entity for the remote is pressed. This was working fine for several months until today.

**What I expected to happen:**
Clicking my remote entity opens the popup with my built remote control

**What happened instead:**
The more info dialog for the entity is opened

**Minimal** steps to reproduce:
1. Create a popup card
2. Populate the popup card with a custom lovelace card
3. Link this to any entity
4. Click the entity

```yaml
type: custom:popup-card
entity: remote.millennium_falcon
dismissable: true
card:
  type: custom:android-tv-card
  remote_id: remote.millennium_falcon
  slider_id: media_player.millennium_falcon
  media_player_id: media_player.millennium_falcon
  keyboard_id: media_player.android_tv_192_168_86_54
  rows:
    - - power
      - search
      - home
    - - emby
      - youtube
      - keyboard
    - - back
      - volume_down
      - volume_up
    - - touchpad
title: Millennium Falcon Remote
```
---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [ X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

### PR DESCRIPTION
**Pull request by sebastian-bartkowiak**
Fixes #719

### CODE REVIEW

**Comment by thomasloven** [comment]
This seems to do it.
Thanks!

**Comment by Starcon79** [comment]
Hello, unfortunately, it still doesn't work for me despite the update.

**Comment by pfiorentino** [comment]
> Hello, unfortunately, it still doesn't work for me despite the update.

Agreed, it works on the HA Android App, but the web version is still not working (Chrome 127 on MacOS Sonoma)

**Comment by thomasloven** [comment]
If you go to the Browser Mod settings page. What does it say in the upper right corner?

**Comment by pfiorentino** [comment]
> If you go to the Browser Mod settings page. What does it say in the upper right corner?

`2.3.1`

I performed the update a few hours ago :) 

Screenshot 2024-08-01 at 22 36 04

**Comment by Starcon79** [comment]
> If you go to the Browser Mod settings page. What does it say in the upper right corner?

**Comment by pfiorentino** [comment]
That being said, it's not worse, it doesn't beak anything.

I don't think we need to revert this PR, it's just not fixing the issue completely.

**Comment by thomasloven** [comment]
Sorry. I realized that number is actually pulled from the wrong source, so it's not necessarily representative of which version is loaded in your browsers cache.

Make sure to do a hard refresh of the cache.

**Comment by Starcon79** [comment]
> Sorry. I realized that number is actually pulled from the wrong source, so it's not necessarily representative of which version is loaded in your browsers cache.
> 
> Make sure to do a hard refresh of the cache.

"Great, it worked. I cleared the cache again, and now the pop-up is working. Thanks."

**Comment by pfiorentino** [comment]
> Sorry. I realized that number is actually pulled from the wrong source, so it's not necessarily representative of which version is loaded in your browsers cache.
> 
> Make sure to do a hard refresh of the cache.

Also worked here! 🎉

I'm 100% sure to have cleared the cache multiple times before writing my first comment yesterday though, very strange 🤔

Anyway! Thanks for your support! ❤️

**Comment by thomasloven** [comment]
> I'm 100% sure to have cleared the cache multiple times before writing my first comment yesterday though, very strange 🤔

That's caching.
It may only work on the tenth try, and then again not on the eleventh...

**Pull request merged**
