### PR TITLE
remove outline borders fixes #615

### LINKED ISSUE #615: Border Intermittently Appears Around Popup Content Section
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

When calling browser_mod.popup, an unwanted border appears around content but then disappears as soon as any part of the screen is touched or clicked.  Best shown with video... https://drive.google.com/file/d/1FEoDnfAHC_t2imiUJbABQVgc9HYr_Le7/view?usp=sharing

The border only shows up when a popup is initially called. Once you touch any part of the screen it disappears. In dark mode the border is white and black in light mode. I believe it may have to do with the styling of the 'content' class (https://drive.google.com/file/d/1JICXklRsgKs5EPizV5kyhnu9UPu__O2C/view?usp=sharing).

The issue first began after the last update (2.3.0) and occurs when using Chrome and Fully Kiosk.

I have eliminated most elements of the theming, i.e., --divider-color and border color. I set them all to transparent and the problem persists.

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

### PR DESCRIPTION
**Pull request by xZetsubou**
fixes #615

### CODE REVIEW

**Comment by shlomki** [comment]
This is not stale, this still continues to be a problem... can we get this merged?

**Comment by codemunkie15** [comment]
Please can this be re-opened and merged? Still seeing this issue...

**Comment by KJThaDon** [comment]
shame

**Comment by storebatfar** [comment]
Still a problem. Please fix it.

**Pull request closed without merging**
